name: Bug Report
description: Report a problem with haskell-tools.nvim
labels: [bug]
body:

  - type: markdown
    attributes:
      value: |
        _Before reporting:_ search [existing issues](https://github.com/MrcJkb/haskell-tools.nvim/issues?q=is%3Aopen+is%3Aissue+label%3Abug).
        See also: [Troubleshooting section of README.md](https://github.com/MrcJkb/haskell-tools.nvim/blob/master/README.md#minimal-config).

  - type: input
    attributes:
      label: "Neovim version (nvim -v)"
      placeholder: "v0.8.0"
    validations:
      required: true
  - type: input
    attributes:
      label: "Operating system/version"
      placeholder: "NixOS 22.05"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Output of :checkhealth haskell-tools"
      render: "console"
      placeholder: |
        Please paste the output here, as it may contain important information for debugging.
    validations:
      required: true
  - type: textarea
    attributes:
      label: "How to reproduce the issue"
      description: |
        Steps to reproduce using a [minimal config](https://github.com/mrcjkb/haskell-tools.nvim/blob/master/troubleshooting/minimal.lua).
      placeholder: |
        mkdir -p /tmp/minimal
        NVIM_DATA_MINIMAL=/tmp/minimal NVIM_APP_NAME="ht-nvim-minimal" -u minimal.lua
        :edit Foo.hs
        4j
        :lua require('haskell-tools').hoogle_signature()
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Expected behaviour"
      description: "Describe the behaviour you expect. May include logs, images, or videos."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Actual behaviour"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Log files"
      placeholder: "https://gist.github.com/MrcJkb/1b0a2c9849b2e1e912fb"
      description: |
        - Upload the log files before and after the problem in a [secret gist](https://gist.github.com/). Paste the URLs to the gist.
        - See the [Troubleshooting section of the readme](https://github.com/MrcJkb/haskell-tools.nvim/blob/master/README.md#logs) for information on how to retreive the log files.
      render: "console"
  - type: textarea
    attributes:
      label: "The minimal config used to reproduce this issue."
      description: |
        Run with `nvim -u minimal.lua`
      placeholder: |
        vim.env.LAZY_STDPATH = '.repro'
        load(vim.fn.system('curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua'))()

        require('lazy.minit').repro {
          spec = {
            {
              'mrcjkb/haskell-tools.nvim',
              version = '^3',
              init = function()
                -- Configure haskell-tools.nvim here
                vim.g.haskell_tools = {}
              end,
              dependencies = {
                -- Uncomment or add any optional dependencies needed to reproduce the issue
                -- 'nvim-telescope/telescope.nvim',
                -- 'akinsho/toggleterm.nvim',
              },
              lazy = false,
            },
          },
        }

        -- do anything else you need to do to reproduce the issue
      render: "Lua"
    validations:
      required: true
